override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override TARGET_PRIMARY_ARCH := target_aarch64
override TARGET_SECONDARY_ARCH := 
override TARGET_ALL_ARCH :=  target_aarch64 
override TARGET_FORCE_32BIT := 
override KERNELDIR := /home/otyshchenko/work/projects/rcar_h3_2_0/build/tmp/work-shared/salvator-x/kernel-build-artifacts
override KERNEL_ID := 4.9.0-yocto-standard
override PVRSRV_MODULE_BASEDIR := /lib/modules/4.9.0-yocto-standard/extra/
override KERNEL_COMPONENTS := srvkm 
override KERNEL_CROSS_COMPILE := aarch64-poky-linux-
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := r8a7795_linux
override PVR_BUILD_TYPE := release
override PVR_SYSTEM := rgx_rcar
override PVR_LOADER := 
override BUILD := release
override DEBUGLINK := 1
override SUPPORT_COMPUTE := 1
override SUPPORT_TLA := 1
override PVR_HANDLE_BACKEND := idr
override SUPPORT_KERNEL_SRVINIT := 1
override SUPPORT_SERVER_SYNC := 1
override SUPPORT_BUFFER_SYNC := 1
override PKG_CONFIG_SYSROOT_DIR := /home/otyshchenko/work/projects/rcar_h3_2_0/build/tmp/sysroots/salvator-x
override PKG_CONFIG_PATH := /home/otyshchenko/work/projects/rcar_h3_2_0/build/tmp/sysroots/salvator-x/usr/lib/pkgconfig:/home/otyshchenko/work/projects/rcar_h3_2_0/build/tmp/sysroots/salvator-x/usr/share/pkgconfig
override SUPPORT_WRAPEXTMEM := 1
override SUPPORT_EXTENSION_REL := 1
override SUPPORT_EGL_EXTENSION_GET_MEMINFO_REL := 1
override ENABLE_DEBUG_LOG_COMMON_REL := 1
